### ISSUE TITLE
[BUG] 无法创建连接，连接页空白

### ISSUE THREAD

**Issue by git1453** [cweijan/vscode-mysql#1052]
版本: 1.86.2 (system setup)
提交: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
日期: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

点击连接数据库按钮之后，页面不显示任何内容。
![image](https://github.com/cweijan/vscode-database-client/assets/83624279/3cf3e646-8671-443c-af57-d794b90b06ad)

**Comment by cweijan** [comment]
你试试重启下vscode, 如果不行, 就要麻烦你打开下开发者工具让我看下日志了.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/32f53fbd-2d6c-4714-858e-4a17b7db9d98)
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a96858cc-f978-40df-becf-e963316e383b)

**Comment by git1453** [comment]
重启不行。

![image](https://github.com/cweijan/vscode-database-client/assets/83624279/f53613ea-b6d8-44de-a214-96d37e9bdb0a)

**Comment by git1453** [comment]
[cweijan.vscode-dm-client]Cannot read properties of undefined (reading '_isDisposed')
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
（匿名） @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
x.onmessage @ localProcessExtensionHost.ts:376
mainThreadExtensionService.ts:82 


TypeError: Cannot read properties of undefined (reading '_isDisposed')
    at h.emit (c:\Users\git1453\.vscode\extensions\cweijan.vscode-dm-client-4.8.4\out\extension.js:9:26720)
    at EventEmitter.<anonymous> (c:\Users\git1453\.vscode\extensions\cweijan.vscode-dm-client-4.8.4\out\extension.js:220:197811)
    at EventEmitter.emit (node:events:514:28)
    at g.value (c:\Users\git1453\.vscode\extensions\cweijan.vscode-dm-client-4.8.4\out\extension.js:9:28464)
    at r.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at S.$onMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:14027)
    at d.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5520)
    at d.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5286)
    at d.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:4376)
    at d.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:3594)
    at g.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:2242)
    at r.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14073)
    at g.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:8051)
    at r.y (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at r.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14073)
    at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:6331)
    at MessagePortMain.emit (node:events:514:28)
    at Object.emit (node:electron/js2c/utility_init:2:2285)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
（匿名） @ rpcProtocol.ts:161
y @ event.ts:1127
fire @ event.ts:1158
fire @ ipc.net.ts:650
x.onmessage @ localProcessExtensionHost.ts:376

**Comment by cweijan** [comment]
谢谢反馈,  这个达梦很久没更新版本了, 我现在已经进行更新.

主更新版本是这个: https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2
