### ISSUE TITLE
Invalid UTF-8 string in BSON document

### ISSUE THREAD

**Issue by NgeKaworu** [cweijan/vscode-mysql#1080]
mongo BSON读取报错，有个密码字段是加密处理的，读取就报错。

日志
BSONError: Invalid UTF-8 string in BSON document
    at cu (c:\Users\NgeKa\.vscode\extensions\cweijan.vscode-mysql-client2-7.1.0\out\node_modules\mongodb.js:1:59959)
    at hu (c:\Users\NgeKa\.vscode\extensions\cweijan.vscode-mysql-client2-7.1.0\out\node_modules\mongodb.js:1:54689)
    at hu (c:\Users\NgeKa\.vscode\extensions\cweijan.vscode-mysql-client2-7.1.0\out\node_modules\mongodb.js:1:55462)
    at hu (c:\Users\NgeKa\.vscode\extensions\cweijan.vscode-mysql-client2-7.1.0\out\node_modules\mongodb.js:1:55622)

尝试过
find({}, {pwd: 0})，无效

**Comment by cweijan** [comment]
谢谢反馈, 会在下个版本禁用utf8验证.

**Comment by cweijan** [comment]
Hi, 尝试下7.1.2版本, 禁用了utf8验证.
