### ISSUE TITLE
[BUG] TypeError getChildren

### ISSUE THREAD

**Issue by LeonISKopp** [cweijan/vscode-mysql#1195]
- Database type and version: Postgresql (v7.5.1)

Everytime when i write some SQL an error appears when type a dot "."

It is always the same Error message:

[ERROR] TypeError: d.getChildren0 is not a function
	at NS.getLcp (c:\Users\l\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.1\out\extension.js:166904:29)
	at async NS.findNodes (c:\Users\l\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.1\out\extension.js:166855:36)
	at async mk.findNodes (c:\Users\l\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.1\out\extension.js:166956:13)
	at async mk.getCompletion (c:\Users\l\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.1\out\extension.js:167713:17)

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version. You can check if you are binding an invalid connection.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/110220b6-57c5-4d1b-95ec-d6bbeea702b7)

**Comment by LeonISKopp** [comment]
I checked my connection and it seems that everything is fine. The error message appears when i write a dot after an alias name. But also in the same time i get all the columns from a table as recommendation, just like it should be i guess. 
![image](https://github.com/cweijan/vscode-database-client/assets/172582633/7d64637c-1b5a-4e0e-892f-56aab43512c7)
It's only the message that pops up everytime. I hope it helps, i don't really see what's causing the issue.

**Comment by cweijan** [comment]
Fixed in verison 7.5.2.
