### ISSUE TITLE
连接hive ，无法查询数据

### ISSUE THREAD

**Issue by welly1717** [cweijan/vscode-mysql#1247]
hive连接正常，可以预览资源树，查询语句报错
2024-08-23 17:34:31 [ INFO] Executing: select * from device_df LIMIT 10
2024-08-23 17:34:31 [ INFO] Result: 10 rows retrieved in 452ms
2024-08-23 17:34:31 [ERROR] TypeError: Cannot read properties of undefined (reading 'parent')
    at Uut (d:\.VSCode\extensions\cweijan.vscode-database-client2-7.5.7\out\extension.js:128849:93)
    at Fde (d:\.VSCode\extensions\cweijan.vscode-database-client2-7.5.7\out\extension.js:128837:7)
    at d:\.VSCode\extensions\cweijan.vscode-database-client2-7.5.7\out\extension.js:128900:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by sinesgq123** [comment]
2024-08-25 00:04:50 [ERROR] TypeError: Cannot read properties of undefined (reading 'parent')
    at Uut (c:\Users\HCRY\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.7\out\extension.js:128849:93)
    at Fde (c:\Users\HCRY\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.7\out\extension.js:128837:7)
    at c:\Users\HCRY\.vscode\extensions\cweijan.vscode-mysql-client2-7.5.7\out\extension.js:128900:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)  同样的问题

**Comment by cweijan** [comment]
谢谢反馈,  已发布7.5.8修复.
