### ISSUE TITLE
[BUG] Can't connect to MariaDb 11.5.2

### ISSUE THREAD

**Issue by rayperea** [cweijan/vscode-mysql#1302]
- Database type and version: MariaDb 11.5.2

After upgrading MariaDb to version 11.5.2, I can no longer connect using the plugin
When trying to connect in VS Code, I get this error:

SqlError: (conn:710425, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 5000ms
	at f.exports.createFatalError (/home/ray/.vscode/extensions/cweijan.vscode-database-client2-7.6.3/out/node_modules/mariadb.js:5:296)
	at a.connectTimeoutReached (/home/ray/.vscode/extensions/cweijan.vscode-database-client2-7.6.3/out/node_modules/mariadb.js:30:245)
	at listOnTimeout (node:internal/timers:583:11)
	at process.processTimers (node:internal/timers:519:7)

On the server, I get this error:

mariadbd[925881]: 2024-10-18 12:14:08 719480 [Warning] Aborted connection 719480 to db: 'testdb' user: 'testdb' host: 'my-host-changed-for-privacy' (Got an error reading communication packets)

I've even tried to use SSH Tunnel and still this this error
mariadbd[925881]: 2024-10-18 12:24:26 730739 [Warning] Aborted connection 730739 to db: 'testdb' user: 'testdb' host: 'localhost' (Got an error reading communication packets)

What's interesting is that if I change the server type to MySQL instead of MariaDb, then it connects without any issues

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 7.6.4.
