### ISSUE TITLE
[BUG]活跃连接无法修改

### ISSUE THREAD

**Issue by Holierboom** [cweijan/vscode-mysql#1358]
- Database type and version:
[ERROR] TypeError: r?.endsWith is not a function
	at So (c:\Users\20577\.vscode\extensions\cweijan.vscode-database-client2-8.0.1\out\extension.js:159236:13)
	at xT.pickConnectNode (c:\Users\20577\.vscode\extensions\cweijan.vscode-database-client2-8.0.1\out\extension.js:176379:13)
	at xT.activeDb (c:\Users\20577\.vscode\extensions\cweijan.vscode-database-client2-8.0.1\out\extension.js:176361:24)
	at mysql.db.active (c:\Users\20577\.vscode\extensions\cweijan.vscode-database-client2-8.0.1\out\extension.js:181809:38)

**Comment by cweijan** [comment]
谢谢反馈, 已发布版本8.0.2修复

**Comment by Holierboom** [comment]
修复速度很快
