### ISSUE TITLE
无法生成随机数据

### ISSUE THREAD

**Issue by izilongwan** [cweijan/vscode-mysql#789]
Type: <b>Bug</b>

2023-03-09 16:09:01.453 [error] TypeError: Cannot read properties of undefined (reading 'nicer')
	at Object.color (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:159152:33)
	at Object.placeholder (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:158903:29)
	at Object.string (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:158857:31)
	at Handler.gen (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:158805:44)
	at d.mock (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:158798:43)
	at JQ.generateValue (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:183021:114)
	at c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:183008:75
	at Array.map (<anonymous>)
	at JQ.<anonymous> (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:183007:60)
	at Generator.next (<anonymous>)
	at s (c:\Users\user\.vscode\extensions\cweijan.vscode-database-client2-6.2.4\out\extension.js:39:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Extension version: 6.2.4
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.47GB free)|
|Process Argv|-n --enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id f24fe983-78b2-424b-b832-a858c79abae1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
pythonms35:30680984

```

</details>

**Comment by cweijan** [comment]
请问下你生成涉及的列类型有哪些.

**Comment by izilongwan** [comment]
> 生成涉及的列类型有哪些.

刚刚改了下类型可以生成, 看来是类型错误
